### ISSUE TITLE
failure deploying skipper.yaml

### ISSUE THREAD

**Issue by seancurran157** [zalando-incubator/kube-ingress-aws-controller#112]
Hello, 

I'm trying to follow the instructions to deploy skipper and I'm getting an error on the first step, 

`kubectl create -f deploy/skipper.yaml`

I get the following error, 
```
The DaemonSet "skipper-ingress" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"component":"ingress"}: `selector` does not match template `labels
```

Is anyone running into this issue? 
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3+coreos.0", GitCommit:"42de91f04e456f7625941a6c4aaedaa69708be1b", GitTreeState:"clean", BuildDate:"2017-08-07T19:44:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by seancurran157** [comment]
looks like its missing a label on the DaemonSet section, could someone validate the below? 

incorrect
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: skipper-ingress
  namespace: kube-system
  labels:
    component: ingress
```

should be 

````
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: skipper-ingress
  namespace: kube-system
  labels:
    application: skipper-ingress
```

thanks
