### ISSUE TITLE
Internal and Internet-Facing Aws-Load-Balancer-Scheme Cannot Coexist

### ISSUE THREAD

**Issue by grifonas** [zalando-incubator/kube-ingress-aws-controller#114]
I just experienced an issue where the Ingress Controller doesn't create an internal/internet-facing ALB stack when the other type already exists.

**How to Reproduce**:
1. Create an ingress with the internet-facing ingress with "zalando.org/aws-load-balancer-scheme: internal" annotation.
2. Create another ingress for the same domain (not the same host) but with "zalando.org/aws-load-balancer-scheme: internet-facing" annotation (or without any annotations at all, internet-facing being the default).
 
**Expected**: 
A new stack gets created as the first one cannot be used due to the fact that it's of a  different scheme.

**What Happens**:
The Ingress Controller doesn't create a new stack and reports the following in its logs: 

```
2017/12/21 20:55:53 Start polling sleep 30s
2017/12/21 20:56:23 Found 2 ingresses
2017/12/21 20:56:23 Found 1 stacks
2017/12/21 20:56:23 Have 1 models
2017/12/21 20:56:23 updated ingress not needed default/my-first-internal-app with DNS name "internal-k8s-the-rest-of-aws-alb-name"
2017/12/21 20:56:23 updated ingress not needed default/my-internet-facing-app with DNS name "internal-k8s-the-rest-of-aws-alb-name"
```
Note that the ALB DNS is that of the original ALB created for the first "internal" app.

I'm using the latest image for the controller:
registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:latest

Here're the Ingress manifests:

 **Internal**:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "my-first-internal-app"
  annotations:
    zalando.org/aws-load-balancer-scheme: internal
  namespace: default
  labels:
    app: "my-first-internal-app"
spec:
  rules:
  - host: "my-first-internal-app.mydomain.com"
    http:
      paths:
      - backend:
          serviceName: "my-first-internal-app"
          servicePort: 80
```

**Internet-Facing**:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "my-internet-facing-app"
  annotations:
    zalando.org/aws-load-balancer-scheme: internet-facing
  namespace: default
  labels:
    application: "my-internet-facing-app"
spec:
  rules:
  - host: "my-internet-facing-app.mydomain.com"
    http:
      paths:
      - backend:
          serviceName: "my-internet-facing-app"
          servicePort: 80
```

I also tried omitting the annotation altogether for the seconds manifest.
Creating the internet facing ALB first leads to the same behaviour in reverse.
