### ISSUE TITLE
No ALB created when deploying a new ingress.

### ISSUE THREAD

**Issue by nicroto** [zalando-incubator/kube-ingress-aws-controller#213]
I am trying to setup skipper on aws with kops and I get all the way down to deploying my ingress, but it unfortunately doesn't get an ALB created for it.

Here are the details of my setup and exactly what I did.

```
kops version
Version 1.10.0
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

I've set all the necessary IAM permissions on nodes through the spec of the cluster and I've added the required cloudLabel:

```yaml
apiVersion: kops/v1alpha2
kind: Cluster
...
spec:
  ...
  cloudLabels:
    kubernetes.io/cluster/<my cluster id>: owned
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "autoscaling:DescribeAutoScalingGroups",
            "autoscaling:AttachLoadBalancers",
            "autoscaling:DetachLoadBalancers",
            "autoscaling:DetachLoadBalancerTargetGroups",
            "autoscaling:AttachLoadBalancerTargetGroups",
            "autoscaling:DescribeLoadBalancerTargetGroups",
            "elasticloadbalancing:DescribeLoadBalancers",
            "elasticloadbalancing:CreateLoadBalancer",
            "elasticloadbalancing:DeleteLoadBalancer",
            "elasticloadbalancing:DescribeListeners",
            "elasticloadbalancing:CreateListener",
            "elasticloadbalancing:DeleteListener",
            "elasticloadbalancing:DescribeTags",
            "elasticloadbalancing:CreateTargetGroup",
            "elasticloadbalancing:DeleteTargetGroup",
            "elasticloadbalancing:DescribeTargetGroups",
            "elasticloadbalancingv2:DescribeTargetGroups",
            "elasticloadbalancingv2:DescribeLoadBalancers",
            "elasticloadbalancingv2:CreateLoadBalancer",
            "elasticloadbalancingv2:DeleteLoadBalancer",
            "elasticloadbalancingv2:DescribeListeners",
            "elasticloadbalancingv2:CreateListener",
            "elasticloadbalancingv2:DeleteListener",
            "elasticloadbalancingv2:DescribeTags",
            "elasticloadbalancingv2:CreateTargetGroup",
            "elasticloadbalancingv2:DeleteTargetGroup",
            "ec2:DescribeInstances",
            "ec2:DescribeSubnets",
            "ec2:DescribeSecurityGroups",
            "ec2:DescribeRouteTables",
            "ec2:DescribeVpcs",
            "acm:ListCertificates",
            "acm:DescribeCertificate",
            "iam:ListServerCertificates",
            "iam:GetServerCertificate",
            "cloudformation:Get*",
            "cloudformation:Describe*",
            "cloudformation:List*",
            "cloudformation:Create*",
            "cloudformation:Update*",
            "cloudformation:Delete*"
          ],
          "Resource": [
            "*"
          ]
        }
      ]
  ...
...
```

Created the security group through the cloudformation template with the proper VPC_ID and cluster name.

Deployed the `skipper.yaml`.
Deployed the `ingress-controller.yaml` with the proper region id.

Then the skipper-ingress pods started failing with:

```
level=error msg="failed to load all: request failed, status: 403, 403 Forbidden"
```

So I started searching for solutions and found this as a fix, which did resolve the problem and both skipper-ingress pods became healthy:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress
rules:
- apiGroups:
  - extensions
  resources:
  - ingresses
  - ingresses/status
  verbs:
  - get
  - list
  - patch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skipper
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list

# kubectl create clusterrolebinding skipper --clusterrole=ingress --serviceaccount=kube-system:default -n kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-system-default-user-role-binding-ingress
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: ingress
  apiGroup: rbac.authorization.k8s.io

# kubectl create clusterrolebinding skipper --clusterrole=skipper --serviceaccount=kube-system:default -n kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-system-default-user-role-binding-skipper
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: skipper
  apiGroup: rbac.authorization.k8s.io
```

And finally I have deployed my ingress, but it doesn't get an ALB (ADDRESS is empty).
Here it is:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: name-of-ingress
  labels:
    app: app-name
    chart: chart-name-0.1.0
    release: release-name
    heritage: Tiller
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: web-front
          servicePort: 80
  - host: api.example.com
    http:
      paths:
      - path: /v0
        backend:
          serviceName: api-gateway
          servicePort: 80
```

I checked the logs on the ingress controller and here is what I see once the ingress has been deployed in my cluster:

```
Start polling sleep 30s
Found 1 ingress(es)
Found 0 stack(s)
Found 1 auto scaling group(s)
Found 0 single instance(s)
Found 2 EC2 instance(s)
Found 2 certificate(s)
Have 1 model(s)
creating stack for certificates ["arn:aws:acm:<omitted>:certificate/<omitted>" "arn:aws:acm:<omitted>:certificate/<omitted>"] / ingress map["arn:aws:acm:<omitted>:certificate/<omitted>":["default/name-of-ingress"] "arn:aws:acm:<omitted>:certificate/<omitted>":["default/name-of-ingress"]]
stack "arn:aws:cloudformation:<omitted>:stack/kube-ingress-aws-controller-<my cluster id>-<omitted>/<omitted>" for certificates ["arn:aws:acm:<omitted>:certificate/<omitted>" "arn:aws:acm:<omitted>:certificate/<omitted>"] created
```

I don't see any errors on the ingress pods. What does "Found 0 stack(s)" and "Found 0 single instance(s)" mean? Is this the problem?

I have been battling with this for many hours now and I am completely out of ideas...

@szuecs what else can I provide for you to give you a better idea of what's going on, here?
