### ISSUE TITLE
Issues with multiple paths

### ISSUE THREAD

**Issue by flmmartins** [zalando-incubator/kube-ingress-aws-controller#226]
Hello All,

I'm using KOPS/Kubernetes-aws-controller/skipper setup similar to what is describe [here](https://github.com/kubernetes/kops/blob/master/addons/kube-ingress-aws-controller/v1.0.0.yaml).

Hitting port 80 pointing to one service is fine.
 
But I also have api running in order port so I used the **same** DaemonSet and Controller as described above but I went to AWS and opened the port 4000 and 4001 (both in sec group and listener load balancer)  and changed my ingress like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: 2018-11-12T11:13:45Z
  name: ${product}-ingress
spec:
  rules:
  - host: "${hostname}"
    http:
      paths:
      - path: /backend
        backend:
          serviceName: backend
          servicePort: 4001
      - path: /connect
        backend:
          serviceName: backend2
          servicePort: 4000
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
```

I can see in the logs that Skipper is redirecting well enough but somehow I can only go to / route and not the other routes above.

Do I need to do something else? Maybe configure target groups?
How can I accomplish these? A solution with ports instead paths would also work for me....

**Comment by szuecs** [comment]
Which skipper version you are using?

As far as I understand you have a setup similar to the one shown in https://opensource.zalando.com/skipper/kubernetes/ingress-controller/#aws-deployment .

For your ingress you do not need to add anything in SecurityGroups, besides the static ones from worker to worker nodes and ALB targetgroup to skipper-ingress.

If skipper finds this ingress it should also create all the routes for the paths you have shown, if not it's a bug in skipper and you should add an issue at https://github.com/zalando/skipper/issues.

Important information would be to add also the routing table that skipper created https://opensource.zalando.com/skipper/tutorials/basics/#current-routing-table use `port-forward` to a skipper pod to 9911 to get the information.

Additionally to test tell who is responding to your requests (http `Server` header in the response) if you call for example /backend with curl.

Feel free to ping me in our slack channel, too: https://github.com/zalando/skipper#community
Thanks!

**Comment by flmmartins** [comment]
Hello, can you give me an example? Cause I've been through the documentation page and I couldn't find

**Comment by szuecs** [comment]
I don’t understand. What kind of example you want to have?

**Comment by flmmartins** [comment]
So without path-prefix all the rotes were redirecting to my frontend app and it was showing a pretty 404 page.

I tried with path-prefix:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    zalando.org/skipper-ingress-path-mode: path-prefix
  creationTimestamp: 2018-11-12T11:13:45Z
  name: company-ingress
  labels:
    infra.name: ${product}-ingress
    infra.component: ingress
    infra.environment: ${environment}
    infra.version: ${version}
    infra.part-of: ${load_balancer_name}
    terraform.module: load_balancer
    product: ${product}
spec:
  rules:
  - host: "${hostname}"
    http:
      paths:
      - path: /
        backend:
          serviceName: my-company-frontend
          servicePort: 80
      - path: /backend
        backend:
          serviceName: my-company-backend
          servicePort: 4001
      - path: /connect
        backend:
          serviceName: company-connect-backend
          servicePort: 4000

```
Now when I tried /backend lit's giving me 404 but not pretty page from our frontend application, it's the 404 from the browser. If I tried to hit /backend/ then the pretty page from our frontend applications gives me a 404 as it was happening before. That's weird.

Doing `kubectl logs -lcomponent=ingress --all-containers=true -n kube-system | grep -v health`

```
[APP]time="2018-11-20T09:14:26Z" level=info msg="Set pathMode to path-prefix"
[APP]time="2018-11-20T09:14:27Z" level=info msg="route settings, update, route: kube_default__company_ingress__demo_company_net___backend__my_company_backend: Host(/^demo[.]company[.]net$/) && PathSubtree(\"/backend\") -> \"http://100.64.200.203:4001\""
[APP]time="2018-11-20T09:14:27Z" level=info msg="route settings, update, route: kube_default__company_ingress__demo_company_net___connect__company_connect_backend: Host(/^demo[.]company[.]net$/) && PathSubtree(\"/connect\") -> \"http://100.66.18.201:4000\""
[APP]time="2018-11-20T09:14:27Z" level=info msg="route settings, update, route: kube_default__company_ingress__demo_company_net_____my_company_frontend: Host(/^demo[.]company[.]net$/) && PathSubtree(\"/\") -> \"http://100.66.114.92:80\""
```

The routes are hitting the corrects IPs in the correct ports.

Other things I've tried:

I've tried to put the backend in / and it works! It hits swagger very well.... so this gotta be something related with paths!

I tried to play with paths by removing the / and using /frontend, /backend and etc...: It ALWAYS give me 404 in all applications.

Somehow I'm not able to used named paths.

I also tried creating subdomains and everything works correctly with subdomains (adding multiple hosts to ingress) but somehow with paths seems to be the issue

**Comment by szuecs** [comment]
Hi! I just tested an ingress with 3 paths similar to yours and checked with deployment with replicas=2 or replicas=1 and it works as expected. 

Can you check that the services you reference are also targeting the right backend as expected?


The test example below works as expected.

## test

### ingress

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    application: sszuecs-demo
  name: sszuecs-demo-kiac-6
  namespace: default
spec:
  rules:
  - host: c6.kiac-test.domain
    http:
      paths:
      - backend:
          serviceName: sszuecs-kiac-backend
          servicePort: 80
        path: /backend
      - backend:
          serviceName: sszuecs-kiac-connect
          servicePort: 80
        path: /connect
      - backend:
          serviceName: sszuecs-kiac
          servicePort: 80
        path: /
```

### 3 services

backend
```
apiVersion: v1
kind: Service
metadata:
  labels:
    application: sszuecs-kiac-backend
  name: sszuecs-kiac-backend
spec:
  ports:
  - name: external
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    application: sszuecs-kiac-backend
  type: ClusterIP
```

connect 
```
apiVersion: v1
kind: Service
metadata:
  labels:
    application: sszuecs-kiac-connect
  name: sszuecs-kiac-connect
spec:
  ports:
  - name: external
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    application: sszuecs-kiac-connect
  type: ClusterIP
```

catchall
```
apiVersion: v1
kind: Service
metadata:
  labels:
    application: sszuecs-kiac
  name: sszuecs-kiac
spec:
  ports:
  - name: external
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    application: sszuecs-kiac
  type: ClusterIP
```

### 3 deployments

catchall
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    application: sszuecs-kiac
  name: sszuecs-kiac
spec:
  replicas: 2
  selector:
    matchLabels:
      application: sszuecs-kiac
  template:
    metadata:
      labels:
        application: sszuecs-kiac
    spec:
      containers:
      - args:
        - skipper
        - -inline-routes
        - '* -> inlineContent("catchall") -> <shunt>'
        image: registry.opensource.zalan.do/pathfinder/skipper:v0.10.112
        imagePullPolicy: IfNotPresent
        name: sszuecs-kiac
        ports:
        - containerPort: 9090
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
```

backend
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    application: sszuecs-kiac
  name: sszuecs-kiac-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      application: sszuecs-kiac-backend
  template:
    metadata:
      labels:
        application: sszuecs-kiac-backend
    spec:
      containers:
      - args:
        - skipper
        - -inline-routes
        - '* -> nlineContent("backend") -> <shunt>'
        image: registry.opensource.zalan.do/pathfinder/skipper:v0.10.112
        imagePullPolicy: IfNotPresent
        name: sszuecs-kiac-backend
        ports:
        - containerPort: 9090
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
```

connect
```apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    application: sszuecs-kiac
  name: sszuecs-kiac-connect
spec:
  replicas: 2
  selector:
    matchLabels:
      application: sszuecs-kiac-connect
  template:
    metadata:
      labels:
        application: sszuecs-kiac-connect
    spec:
      containers:
      - args:
        - skipper
        - -inline-routes
        - '* -> inlineContent("connect") -> <shunt>'
        image: registry.opensource.zalan.do/pathfinder/skipper:v0.10.112
        imagePullPolicy: IfNotPresent
        name: sszuecs-kiac-connect
        ports:
        - containerPort: 9090
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

```

**Comment by flmmartins** [comment]
I was checking the files and my Service the type is NodePort... also my TargetPort and port are 4000 4000. Could that be affecting it? Best,

**Comment by flmmartins** [comment]
> @flmmartins I am not sure, but try to have a clusterIP service. In the end you won't need the nodeport service anyways.

In my case I think need it.. because I there's Swagger Web Page... so I need external access for backends.

**Comment by szuecs** [comment]
@flmmartins can't Swagger API Web Page use the same ingress or a second ingress to expose the swagger API?
Maybe I miss understood something?

**Comment by flmmartins** [comment]
> @flmmartins can't Swagger API Web Page use the same ingress or a second ingress to expose the swagger API?
> Maybe I miss understood something?

I tried using different ingresses.... but maybe I did something wrong.... can you give me an example?

**Comment by szuecs** [comment]
@flmmartins would you mind showing us an example of your setup, please?
It's hard to guess what you try to achieve.

In general if you have 2 different endpoints with 2 different TCP ports in your Pod, you can use 2 ingress to expose both:

Assuming you have pods that expose 2 ports and are selected via 2 Kubernetes services foo-web with port 8080, foo-swagger with port 9090, then these 2 ingress should route the traffic correctly to your endpoints (containers).

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: foo-web
  namespace: default
spec:
  rules:
  - host: foo.example.org
    http:
      paths:
      - backend:
          serviceName: foo
          servicePort: 8080
``` 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: foo-swagger
  namespace: default
spec:
  rules:
  - host: foo.example.org
    http:
      paths:
      - path: /swagger-path
        backend:
          serviceName: foo-swagger
          servicePort: 9090
```
