### ISSUE TITLE
Cloudformation is always trying to change the certificates every 5 minutes

### ISSUE THREAD

**Issue by flmmartins** [zalando-incubator/kube-ingress-aws-controller#251]
Hello All,

I had to add/delete mutiple certificates manually to the load balancer (v0.8.0) and I was looking at the Cloud Formation Stack and it's trying to delete them.

```
11:29:33 UTC+0200 | UPDATE_ROLLBACK_COMPLETE | AWS::CloudFormation::Stack | Update successful. One or more resources could not be deleted.
  | 11:29:31 UTC+0200 | DELETE_FAILED | AWS::ElasticLoadBalancingV2::ListenerCertificate | HTTPSListenerCertificated | Default certificate cannot be removed (Service: AmazonElasticLoadBalancingV2; Status Code: 400; Error Code: OperationNotPermitted; Request)
  | 11:29:25 UTC+0200 | DELETE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::ListenerCertificate | HTTPSListenerCertificated
```

And this goes one every 5 minutes or so

I was looking how to add them to the stack to avoid this behaviour of trying to delete and I saw this in the documentation:

```
annotations:
    zalando.org/aws-load-balancer-ssl-cert: arn:aws:acm:eu-central-1:123456789012:certificat

```

Can I add more than one? Like an array of some sorts? How?

**Comment by szuecs** [comment]
The controller tries to add all valid certificates that are wanted via `hostname` in ingress to the https listener, that it finds in your account. If you change the CF stack manually, you might create issues in how CF is handled by AWS. The controller will always delete these if no ingress wants to have these.

**Comment by flmmartins** [comment]
When I mentioned manual change I mean that I went in AWS console and added certificates not in CF stack.

I have two names that should point to same load balancer
server.zone.net and server.marketing.com. I need both to be used by Load Balancer.

server.zone.net has a wildcard certificate (*.zone.net) and it's own server.zone.net cause that is only used by teams and the server.marketing.com has it's own certificate.

It is working at the moment. My problem is the certificates.... can I add more than one ssl-cert like:

annotations:
    zalando.org/aws-load-balancer-ssl-cert: arn:aws:acm:eu-central-1:123456789012:*.zone.net, arn:aws:acm:eu-central-1:123456789012:server.zone.net, 
arn:aws:acm:eu-central-1:123456789012:server.marketing.com

???

**Comment by szuecs** [comment]
Ah ok, so you just added certificates manually in ACM, which is fine.
If you then have 2 ingress or 2 hostnames in one ingress:
- `server.zone.net`
- `server.marketing.com`
the https listener will get both certificates attached and the https client will send the requested hostname via SNI, such that the ALB httpsListener can present the right certificate to the user.

There is no need to use the  `zalando.org/aws-load-balancer-ssl-cert` annotation anymore.

This would work, for example without annotations:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
spec:
  rules:
  - host: server.zone.net
    http:
      paths:
      - backend:
          serviceName: app-svc
          servicePort: 80
  - host: server.marketing.com
    http:
      paths:
      - backend:
          serviceName: app-svc
          servicePort: 80
```
