### ISSUE TITLE
Support for Cloudwatch Alarm configuration

### ISSUE THREAD

**Issue by martinohmann** [zalando-incubator/kube-ingress-aws-controller#271]
We'd like to automatically set up Cloudwatch Alarms for certain ALB metrics (e.g. `RejectedConnectionCount`) to be able to get better visibility of problems that might occur between the ALBs and the actual ingress controller (nginx-ingress-controller in our case).

I was thinking about making Cloudwatch Alarms configurable in an optional ConfigMap which would then be rendered into the Cloudformation template for the ALBs.

Is this a feature that you would find useful? I'd be willing to work on it and provide you with a PR.

**Comment by szuecs** [comment]
@martinohmann can you show how the data could look like that you imagine to configure Cloudwatch Alarms for an ingress?

Right now I would recommend to try to use ingress annotations, because the state is only in one place, but maybe it makes sense in this case. :)

**Comment by martinohmann** [comment]
Sadly, ingress annotations are not flexible enough for this feature because each Cloudwatch Alarm has quite a few fields that can be/need to be configured.

Here is the documentation for the CW Alarm fields that can be set via Cloudformation: https://docs.aws.amazon.com/en_us/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html#aws-properties-cw-alarm-syntax.yaml

There are basically only two fields that can be left out, because they can be inferred while generating the cloudformation template: `Namespace` is always `AWS/ApplicationELB` and `Dimension` would only contain one key-value pair which is `LoadBalancerName: <generated-alb-name>` and which would be filled while rendering the CF template.

A ConfigMap for that could look like this:
```
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-ingress-aws-controller-alarms
  namespace: kube-system
data:
  alarms: |
    - ActionsEnabled: true
      AlarmActions: 
      - arn:aws:sns:region:account-id:sns-topic-name
      AlarmDescription: "Some description of the alarm"
      AlarmName: "Some alarm"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 2
      EvaluateLowSampleCountPercentile: evaluate
      EvaluationPeriods: 1
      ExtendedStatistic: String
      InsufficientDataActions: 
      - arn:aws:sns:region:account-id:sns-topic-name
      MetricName: RejectedConnectionCount
      OKActions: 
      - arn:aws:sns:region:account-id:sns-topic-name
      Period: 600
      Statistic: Maximum
      Threshold: 50
      TreatMissingData: notBreaching
      Unit: Count
    - ActionsEnabled: true
      AlarmActions: 
      - arn:aws:sns:region:account-id:sns-topic-name
      AlarmDescription: "Some description of the alarm"
      AlarmName: "Some other alarm"
      [...]
```

If we stick to the same Schema as in the Cloudformation docs this should be fairly easy to implement, validate and maintain. We might even be able to unmarshal it directly into the corresponding go-type https://godoc.org/github.com/crewjam/go-cloudformation#CloudWatchAlarm.

The path to the config map could be configurable via CLI flag, e.g `--cloudwatch-alarms-configmap=kube-system/kube-ingress-aws-controller-alarms`.

What do you think?
