### ISSUE TITLE
v0.8.14: http -> https redirection causes an endless loop

### ISSUE THREAD

**Issue by icy** [zalando-incubator/kube-ingress-aws-controller#310]
Hi, 

I'm using the controller version 0.8.14,and the daemon is started as below

```
    spec:
      serviceAccountName: kube-ingress-aws
      containers:
      - args:
        - "-ip-addr-type=ipv4"
        - "-health-check-port=30081"
        - "-health-check-path=/kube-system/healthz"
        - "-health-check-interval=10s"
        - "-target-port=30081"
        - "-ingress-class-filter=nginx-internal"
        - "-controller-id=nginx-internal"
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:v0.8.14
        name: controller
```

I am trying to use the annotation for the ingress object as below

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-apse1
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    zalando.org/aws-load-balancer-scheme: internal
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: prometheus-apse1.example.net
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus-apse1
          servicePort: 80
```

After applying the configuration, I got the loop

https://gist.github.com/icy/d852c7bd02891c2b159d14fa5f4c41e6

This happens to all Ingress on the system, not only the new one I have created.

Is that I'm missing something? Is this a bug and/or a known feature?

Thanks a lot.
