### ISSUE TITLE
internal load balancer not creating when SSL doesnt exist

### ISSUE THREAD

**Issue by sean-mcgimpsey** [zalando-incubator/kube-ingress-aws-controller#352]
For some internal resources we do not require SSL (internal domains). This seems to cause an issue with the controller, as it refuses to create an ALB if the path defined in an apps ingress manifest does not match an existing certificate.

For example 
```
### Snipper from ingress def
spec:
  rules:
  - host: dash.example.domain.internalonly # not public, no ssl. 
    http:
      paths:
      - backend:
          serviceName: dash-kubernetes-dashboard
          servicePort: 80
        path: /
```

When this resource is created, the controller will output the below errors and does not create any LB.
```
time="2020-04-29T10:35:53Z" level=error msg="Failed to find certificate for hostname dash.maru.dev.internal: no matching certificate found"
time="2020-04-29T10:35:53Z" level=error msg="No certificates found for [dash.example.domain.internalonly]"
```

Is there a way around this, or, does it require that an SSL certificate exists?

Thanks
