### ISSUE TITLE
How to set up Ingress controller together with Kube2iam -  NoCredentialProviders: no valid providers in chain

### ISSUE THREAD

**Issue by tomekit** [zalando-incubator/kube-ingress-aws-controller#409]
This isn't bug, but rather help needed.

After I've installed Kube2Iam, I am having problems with: `kube-ingress-aws-controller` failing with:
```
time="2021-03-23T15:16:48Z" level=info msg="starting /kube-ingress-aws-controller v0.11.21"
time="2021-03-23T15:16:49Z" level=fatal msg="unable to get details for instance \"i-<instanceId>\": NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
```

In controller `deployment` I've added relevant annotation (which has proper `role` configured in my AWS account):
```
annotations:
        iam.amazonaws.com/role: arn:aws:iam::<awsAccountId>:role/kube2iam-ingress-aws
```
however this hasn't resolved my issue. 

I know that this is maybe more of a `kube2iam` issue, than `kube-ingress-aws-controller`, on the other hand I am posting it here, as I would assume that it's pretty common combination.

Is there anything else that needs to be done in order for this pair to work?

Using annotation as shown above I've successfully given proper AWS IAM to `external-dns` service. The only difference is that `kube-ingress-aws-controller` sits in the `kube-system` namespace where as my `external-dns` doesn't use namespace.
Are there any additional steps in order to give IAM to deployment running in a namespace?

Any help much appreciated.

UPDATE:
Technically `kube2iam` assigned the role correctly.
When I manage to `/bin/sh` inside the controller and call: `curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials` I get the valid role returned: `arn:aws:iam::<awsAccountId>:role/kube2iam-ingress-aws`

**Comment by jonathanbeber** [comment]
If you have the role as you was able to debug and show in your update, it should work. Of course, there're other errors that might happen in the process of communicating with the metal credentials service. Does it happen every time? Did you try starting the binary after you executed the `curl`? I wonder if it's a problem with the credentials not being available on the startup time because we don't retry to get the instance details and exit with `fatal`.

**Comment by jonathanbeber** [comment]
Actually, we do retry and 3 times and if you start the controller with debugging, we also set AWS client to debug mode: https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/aws/adapter.go#L167-L180

Can you try starting it in debug mode?

**Comment by tomekit** [comment]
Thank you for your fast response. Actually the annotation configuration above is all correct, and there isn't any issue with: `kube-ingress-aws-controller` or the fact that it runs in `kube-system` namespace.

I've failed to set up correct Trust Relationship: http://stackoverflow.com/a/33850060 and haven't realized that `external-dns` (that I've mentioned it works correctly, as a proof of valid `kube2iam` setup) actually stopped working as well.

For anyone affected. If you have a role prepared for your: `kube-ingress-aws-controller` and role that's assigned to your Kubernetes worker node (in my case for `kops` that's `nodes.<clusterName`, then you need to set up correct trust policy for: ` `nodes.<clusterName` where you need to list your ingress role in the `Principal` part of trust policy. As per: https://github.com/jtblin/kube2iam

To further debug this issue you can spin up `awscli` image running in host network:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-iam
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: test-iam
  template:
    metadata:
      labels:
        app: test-iam
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::307674252388:role/kube2iam-external-dns
    spec:
      hostNetwork: true
      containers:
        - name: test-iam
          command: ["/bin/bash"]
          args: ["-c", "trap : TERM INT; sleep infinity & wait"]
          image: amazon/aws-cli:latest
```

then after `kubectl exec -it <podName> /bin/bash` you can execute: `aws sts assume-role --role-arn arn:aws:iam::<accountId>:role/kube2iam-ingress-aws --role-session-name asd`
you should receive valid credentials. In case of a failure you will get: `An error occurred (AccessDenied) when calling the AssumeRole operation: User: ... is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::<accountId>:role/kube2iam-ingress-aws`

Writing it down for someone who like myself didn't use `AssumeRole` earlier
