### ISSUE TITLE
Consider using CloudFormation to create managed ALBs

### ISSUE THREAD

**Issue by lmineiro** [zalando-incubator/kube-ingress-aws-controller#42]
The current approach to create Application Load Balancers is not an atomic operation.

If we fail to create either the TargetGroup or the Listener(s) we'll leave an inconsistent ALB in place.

We should explore using CloudFormation templates for this to do this as a single, atomic, operation.

**Comment by lmineiro** [comment]
As expected, the first tests I did locally show that using CloudFormation can be used instead of individual API calls.
The good part is that we're able to get atomicity creating ALB + TargetGroup + Listener, attaching the ASG to the TargetGroup still needs to be a separate, non-atomic call.
The bad part is that creating a stack is an asynchronous call. There are API calls to do short polling and wait for the results. During my tests I observed times between 2min and more.
This is enough to force a rethinking of the strategy. I'd like to avoid unnecessary complexity but, on the other hand, we should prevent nasty things like race conditions (it's the major point for this change).
Last but not least, I'd like to hear opinions on the preferred way to deploy the CF template alongside the binary. I'm more inclined to provide an external YAML file (I created it properly parametrized to be used "as is") but we can also paste it into a Go const if this is ideal. Let me know your thoughts @hjacobs @szuecs @Raffo @mikkeloscar @linki @ideahitme @tuxlife

**Comment by lmineiro** [comment]
CF Template draft:
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: "Kubernetes Ingress for AWS Controller: Load Balancers stack"
Parameters:
    ClusterIDParameter:
        Type: String
        Description: The ClusterID value used to tag resources
    LoadBalancerNameParameter:
        Type: String
        Description: The new Load Balancer Name
        MaxLength: 32
    LoadBalancerSecurityGroupParameter:
        Type: AWS::EC2::SecurityGroup::Id
        Description: The security group ID for the Load Balancer
    LoadBalancerSubnetsParameter:
        Type: List<AWS::EC2::Subnet::Id>
        Description: The list of subnets IDs for the Load Balancer
    TargetGroupHealthCheckPathParameter:
        Type: String
        Description: The healthcheck path
        Default: /kube-system/healthz
    TargetGroupHealthCheckPortParameter:
        Type: Number
        Description: The healthcheck port
        Default: 9999
    TargetGroupVPCIDParameter:
        Type: AWS::EC2::VPC::Id
        Description: The VPCID for the TargetGroup
    ListenerCertificateParameter:
        Type: String
        Description: The HTTPS Listener certificate ARN (IAM/ACM)
        Default: ""

Conditions:
    CreateHTTPSListener: !Not [ !Equals [ !Ref ListenerCertificateParameter, "" ] ]
    
Resources:
    ALBHTTPListener:
        Type : AWS::ElasticLoadBalancingV2::Listener
        Properties:
            DefaultActions:
                - Type: forward
                  TargetGroupArn: !Ref ALBTargetGroup
            LoadBalancerArn: !Ref IngressLoadBalancer
            Port: 80
            Protocol: HTTP

    ALBHTTPSListener:
        Type : AWS::ElasticLoadBalancingV2::Listener
        Condition: CreateHTTPSListener
        Properties:
            DefaultActions:
                - Type: forward
                  TargetGroupArn: !Ref ALBTargetGroup
            LoadBalancerArn: !Ref IngressLoadBalancer
            Port: 443
            Protocol: HTTPS
            Certificates:
                - CertificateArn: !Ref ListenerCertificateParameter

    IngressLoadBalancer:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Name: !Ref LoadBalancerNameParameter
            SecurityGroups:
                - !Ref LoadBalancerSecurityGroupParameter
            Subnets: !Ref LoadBalancerSubnetsParameter
            Tags:
                - Key: Name
                  Value: !Ref LoadBalancerNameParameter
                - Key: ClusterID
                  Value: !Ref ClusterIDParameter
                - Key: kubernetes:application
                  Value: kube-ingress-aws-controller
                - Key: kubernetes:application:method
                  Value: atomic-cloudformation

    ALBTargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
          HealthCheckPath: !Ref TargetGroupHealthCheckPathParameter
          Port: !Ref TargetGroupHealthCheckPortParameter
          Protocol: HTTP
          Name: !Ref LoadBalancerNameParameter
          VpcId: !Ref TargetGroupVPCIDParameter

Outputs:
    LoadBalancerARN:
        Description: The ARN of the LoadBalancer
        Value: !Ref IngressLoadBalancer
    LoadBalancerDNSName:
        Description: DNS name for the LoadBalancer
        Value: !GetAtt IngressLoadBalancer.DNSName
    TargetGroupARN:
        Description: The ARN of the TargetGroup
        Value: !Ref ALBTargetGroup
    HTTPListenerARN:
        Description: The ARN of the HTTP Listener
        Value: !Ref ALBHTTPListener
    HTTPSListenerARN:
        Description: The ARN of the HTTPS Listener
        Value: !Ref ALBHTTPSListener
```
