### ISSUE TITLE
Kube Ingress AWS Controller pod is using stale tokens

### ISSUE THREAD

**Issue by wilkejo** [zalando-incubator/kube-ingress-aws-controller#535]
Hello,

the "Bound Service Account Token Volume" is graduated to stable and enabled by default in AWS EKS version 1.21.
I am using "registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:v0.13.3 " in AWS EKS 1.21 and I have checked, if it is using stale tokens (regarding https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html and https://docs.aws.amazon.com/eks/latest/userguide/troubleshooting.html#troubleshooting-boundservicetoken).

Version:

registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:v0.13.3

Cluster Details

AWS EKS 1.21

Steps to reproduce issue

Enable EKS Audit Logs
Query CW Insights (select cluster log group):
fields @timestamp
| filter @message like /seconds after warning threshold/
| parse @message "subject: *, seconds after warning threshold:*\"" as subject, elapsedtime

- This issue is basically a copy from this issue: https://github.com/fluxcd/helm-controller/issues/479

However I don't have the annotation on my pods in EKS 1.21. I can see that the token age is older than one hour via the CW query

@timestamp                                     subject                                                                                        elapsedtime
2022-08-24T16:25:33.659+02:00    system:serviceaccount:...:kube-ingress-aws-service-account    30264

Thank you!

**Comment by mikkeloscar** [comment]
For anyone looking to work on this!

This is about changing how the token for connecting the Kubernetes APIserver is read and refreshed. We did something very similar for skipper. See https://github.com/zalando/skipper/issues/1277 and https://github.com/zalando/skipper/pull/1295

**Comment by demonCoder95** [comment]
PR is up to resolve the issue ^

**Comment by demonCoder95** [comment]
Rolling out the update to `dev`.

**Comment by demonCoder95** [comment]
@wilkejo The new image with the patch for refreshing tokens is up. Make sure to use the new registry. You can find the new image here: 
```bash
container-registry.zalando.net/teapot/kube-ingress-aws-controller:v0.13.18
```

Let me know when you verify that this fixes your problem 🙂 Thank you! I'll continue to roll the patch in our k8s as well since we need it as part of the version upgrade.

**Comment by mikkeloscar** [comment]
@demonCoder95 The image on `container-registry.zalando.net/` is internal to Zalando. The public image is: `registry.opensource.zalan.do/teapot/kube-ingress-aws-controller:v0.13.18`

**Comment by demonCoder95** [comment]
Ah I see 🙂
I guess in the pipeline we push the new image to both registries. (noted)📝

**Comment by wilkejo** [comment]
Hello @demonCoder95 thank you for the work. I deployed it to our dev cluster and unfortunatly it isn't working. 
```shell
time="2022-09-20T13:58:52Z" level=info msg="Updated secret file: /var/run/secrets/kubernetes.io/serviceaccount/token"   
time="2022-09-20T13:58:52Z" level=error msg="failed to list ingress resources: failed to get ingress list: secret not found: token"
```
I saw in your merge request that you wrote `this uses the [skipper/secrets](https://github.com/zalando/skipper/tree/54ff9d009ad4e09295480f51c8d7ec0afeb2be67/secrets) module` We don't have skipper deployed. Is this related?

We are using AWS IAM Service Account Tokens (IRSA), e.g.
```yaml
apiVersion: v1                                                                                                                                                                                                  
kind: ServiceAccount                                                                                                                                                                                            metadata:                                                                                                                                                                                                          
  name: kube-ingress-aws-service-account                                                                                                                                                                           
  annotations:                                                                                                                                                                                                  
     eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT-ID:role/ROLE-NAME
```
