### ISSUE TITLE
Specify custom certificate by name instead of ARN

### ISSUE THREAD

**Issue by schlomo** [zalando-incubator/kube-ingress-aws-controller#81]
# Use Case

Run a service behind a CNAME entry in another DNS domain.

## Example

An AWS account contains Route 53 zone for aws.company.com, DNS for company com is managed manually somewhere else. A service should run under myservice.aws.company.com but be reachable under myservice.company.com.

The AWS account also contains an ACM for `*.company.com`. We need an easy way to specify that ACM without the need to specify the full ARN.

**Example Ingress To Implement**
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingress
  annotations:
    zalando.org/aws-load-balancer-ssl-cert-domain: example.org
spec:
  rules:
  - host: test-app.example.org
    http:
      paths:
      - backend:
          serviceName: test-app-service
          servicePort: main-port
```
